### ISSUE TITLE
ELF section name

### ISSUE THREAD

**Issue by 4e554c4c** [phil-opp/multiboot2-elf64#10]
I'm willing to do this but I'll need to read some more on ELF64 first. I think that it is useful for debugging purposes to see which sections are what easily. If I understand correctly how getting strings works the string table address is in the ELF multiboot tag, and the indices to section names reside in the sections themselves. I suppose that there can be a `pub fn name(&self, *const StrTable)` or something similar but I'm not sure if this is the best option. Feel free to suggest.

**Comment by phil-opp** [comment]
Implemented in #14
