### ISSUE TITLE
Returned strings include null terminator?

### ISSUE THREAD

**Issue by remexre** [phil-opp/multiboot2-elf64#11]
If you e.g. `writeln!(serial, "{:?}", info.boot_loader_name_tag().unwrap().name())`, you get `"GRUB 2.02~beta3\u{0}"` instead of just `"GRUB 2.02~beta3"`. Is this incorrect behavior? (It's unexpected, at least).

**Comment by phil-opp** [comment]
Thanks for reporting! 

I think that we just forgot to strip the null byte. Or am I missing something here, @Ketsuban?
