### ISSUE TITLE
No multiboot module support

### ISSUE THREAD

**Issue by 4e554c4c** [phil-opp/multiboot2-elf64#7]
Hey, thanks for this crate.
I'm willing to implement this, but if you don't want it in your repository I can do it in my own fork.

**Comment by phil-opp** [comment]
You mean the module tag, which indicates loaded boot modules (section 3.4.6 in the [multiboot specification](http://nongnu.askapache.com/grub/phcoder/multiboot.pdf))? I would be happy to merge a PR for that :).
